version: "3.1"
services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    networks:
      - redmine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: Greeme
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - redmine
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  redmine:
    container_name: redmine_container
    image: redmine:latest
    restart: always
    networks:
      - redmine
    volumes:
      - redmine-data:/usr/src/redmine/files
      - redmine-themes:/usr/src/redmine/public/themes
    environment:
      REDMINE_DB_POSTGRES: postgres
      REDMINE_DB_USERNAME: admin
      REDMINE_DB_DATABASE: Greeme
      REDMINE_DB_PASSWORD: admin123
    ports:
      - 80:3000
volumes:
  postgres-data:
  redmine-data:
  redmine-themes:
  pgadmin-data:
networks:
  redmine:
    driver: bridge
